server:
  port: 9000

spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: advertise-service
  zipkin:
    base-url: http://localhost:9411
#  datasource:
#    url: jdbc:mysql://localhost:3306/olxadvertisedb
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#  jpa:
#    hibernate.ddl-auto: update
   
resilience4j:
  circuitbreaker:
    instances:
      AUTH_TOKEN_VALIDATION:
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s
eureka:
  client:
    register-with-eureka: true