server:
  port: 8888

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vijayjejurkar/olx-config
          username: vijayjejurkar
          password: 
          clone-on-start: true
          default-label: master
